{{- if and (not .Values.masterKey.existingSecret) .Values.masterKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-master-key
  labels:
    {{- include "litellm.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  master-key: {{ .Values.masterKey.value | quote }}
{{- end }}
